indexmap-rs/indexmap

- Cargo.toml
- src/lib.rs
I think the case hash maps being smaller than 2<sup>32</sup> elements is pretty common.
> Optimize for "small" maps (capacity fits in 32 bits)

- src/lib.rs
Since the removal operation is an inverse of insertion, removal does back-shift, and back-shift is an inverse of forward-shift ... you get the meaning of this change. The phase 2 of insertion can be just a forward-shift.
The new behavior displaces all elements by 1, in contrast to the old behavior which may displace some elements by more than 1 and leave the rest in the same place.
I didn't include the commit https://github.com/pczarn/ordermap/commit/a64f0fd9de49bd09e4b68ccaaccd05483a964ca4, which doesn't improve anything. If you have time, please look into generated code. With that third commit, there might be a way to merge 2 of 3 branches of the control flow with some elaborate trick.
Now benchmarks. I'm not sure why lookups seem to get faster. I think their timings have high variance. …
> Simplified insert_phase_2

- src/lib.rs
Hi @bluss 
This PR implements method `is_empty`.
Cc #19
> Implement method .is_empty()

- src/lib.rs
Hello again!
This PR implements traits `PartialEq` and `Eq`. :grinning: 
Cc #19
> Implement PartialEq and Eq

- .gitignore
- src/lib.rs
- tests/quick.rs
Problem:
Porting some code that used HashMap's drain to OrderMap revealed a small
API gap.
Solution:
Added a drain method, mostly mirroring what std::collections::HashMap
offers except returning a standard Vec instead of a Drain.
drain() provides an efficient way to remove all values without shrinking
the capacity of the original OrderMap.
Validation:
Added unit tests and ported an existing HashMap::drain() user to
OrderMap::drain
> Adds a OrderMap::drain() method

- src/lib.rs
This allows people to just use `.len()` on the iterators.
> Added ExactSizeIterator support.

- Cargo.toml
- src/lib.rs
- src/serde.rs
- tests/serde.rs
Note that this is not ready for merging, as it doesn't run Travis tests. I'm not sure what should be testing strategy?
> Implement optional Serde 1.0 support

- benches/faststring.rs
- src/lib.rs
This shrinks struct OrderMap by one usize; A boxed slice is a good pick
since the indices are always at len == capacity of the collection.
Fixes #16
> Use Box<[Pos]> for indices array

- src/lib.rs
This matches `hash_extend_copy` feature stabilized in Rust 1.4.0 introduced by https://github.com/rust-lang/rust/pull/28094. Note that this may affect type inference.
> Implement Extend<(&K, &V)> for Copy types

- src/lib.rs
- src/mutable_keys.rs
- src/util.rs
- tests/quick.rs
- Remove get_pair, and rename get_pair_index to get_full. Same with the
mutable variant.
- Move mutable key methods to MutableKeys -- we want this feature to be
out of the way, but opt-in. The trait has mutable key-versions of
get_full and retain
Fixes #7
> Add trait MutableKeys

- src/lib.rs
I implemented the `index()` method for `VacantEntry` that just returns `self.map.len()` and for `Entry`.
I also added a test for some of the functions provided by the Entry API
> index() method for Entry and VacantEntry plus test coverage for Entry API

- src/lib.rs
- src/macros.rs
- src/serde.rs
- src/set.rs
- tests/serde.rs
- tests/tests.rs
An `OrderSet<T>` wraps an `OrderMap<T, ()>`, and also adds set-like
functionality: union, intersection, etc.
The type and all of its supporting iterators are defined in the public
`set` module, and `OrderSet` is re-exported at the crate root.  There is
also a new `orderset!` macro for construction.
Fixes #8.
> Add OrderSet

- README.rst
- Fix typos
- Change wordings
- Maintain a certain degree of consistency in punctuation marks, verbatim style usage, methods syntax and username syntax when making references
> Tweak README

- src/lib.rs
- src/mutable_keys.rs
- src/set.rs
- tests/quick.rs
- Having a retain that keeps the order is very useful
- This is slower across the board but especially if we retain most of the map; the swap_remove version (unordered version) just moves much less values around, even less than a regular `Vec::retain`.
- This PR uses a trick (tombstones in self.indices!) for the duration of the retain method only
> Make .retain() in-order and preserve-order

- benches/bench.rs
- src/lib.rs
- src/mutable_keys.rs
- tests/quick.rs
The new retain was just merged yesterday, but some successive improvements and tweaks of this code resulted in the following much simpler and more efficient version.
- Remove `.retain_unordered()` again (this method has been in no released version), because regular in order retain is the fastest anyway for many cases. Unlike `retain`, users can reimplement `.retain_unordered` externally using the available public methods.
Improvement in this PR:
```
name                                    63 ns/iter  62 ns/iter  diff ns/iter   diff % 
few_retain_ordermap_100_000             3,789,865   2,650,688     -1,139,177  -30.06% 
half_retain_ordermap_100_000            3,928,837   2,735,071     -1,193,766  -30.38% 
many_retain_ordermap_100_000            3,574,726   2,332,965     -1,241,761 …
```
> Simplify and speed up the in-order preserve-order `.retain()`

- benches/bench.rs
- benches/faststring.rs
- src/lib.rs
- src/set.rs
- tests/quick.rs
Implement an in place sorting method for OrderMap (and OrderSet). We use a very neat trick and temporarily save away the hash for each entry somewhere else and store the old index in the hash field. The benefit is that we can use `self.entries.sort_by` directly after that, which is very fast.
I don't think the extra allocation is avoidable (but we could have unstable sort too, avoiding *an* allocation).
Benchmarks from the current version, `sort` is the sorting algorithm in this PR. 
```rust
test ordermap_simple_sort_s                ... bench:   3,169,240 ns/iter (+/- 180,707)
test ordermap_simple_sort_u32              ... bench:     845,610 ns/iter (+/- 54,359)
test ordermap_sort_s                       ... bench:   2,550,010 ns/iter (+/- 279,423)
test ordermap_sort_u32 …
```
> Implement sorting in place for OrderMap, OrderSet

- src/lib.rs
- src/mutable_keys.rs
- src/set.rs
For each compiled item we ideally want it to depend on the least amount of type parameters, so that it can be shared between different parameterizations of OrderMap. To this end, factor out the part of ordermap that does not depend on S (the hasher). This also seems like a cleaner design, even if it needs some more wrapper methods.
As a bonus, this resolves the issue where we had one more parameter than the standard `HashMap`'s `Entry<K, V>` -- ordermap's entry is now identical.
Also reduce the number of closures used in the iterators.
> Factor out "OrderMapCore" and other generics bloat saving measures

- README.rst
- src/lib.rs
- src/map.rs
- src/set.rs
The idea is to introduce deprecations and IndexMap type aliases in 0.4.1
> Docs & Relnote for ordermap 0.4.0 (the last release series under this name)

- src/lib.rs
- src/map.rs
- src/mutable_keys.rs
- src/set.rs
It's possible to put the deprecation on the crate itself, but then users
get a ridiculous onslaught of messages for each item (including methods)
used from the crate. So we put the notice on OrderMap and OrderSet
themselves.
> Add deprecation notice to OrderMap/Set to prepare for rename to indexmap

- Cargo.toml
- README.rst
- benches/bench.rs
- benches/faststring.rs
- src/lib.rs
- src/macros.rs
- src/map.rs
- src/mutable_keys.rs
- src/serde.rs
- src/set.rs
- tests/equivalent_trait.rs
- tests/quick.rs
- tests/serde.rs
- tests/tests.rs
- `OrderMap` becomes `IndexMap` with no change in functionality
- Releasing version 1.0 of the crate becomes possible shortly after the rename
- This is the big rename; see discussion and rationale in issue #14
Plan:
1. Release ordermap 0.4.1 with a deprecation message pointing to indexmap; in PR #64
2. Release indexmap 0.4.1 with the rename (and deprecated type aliases in place for OrderMap/Set) (this PR)
3. Release indexmap 1.0 with deprecated items removed. (later)
Fixes #14
> Rename OrderMap to IndexMap; rename crate to indexmap (and OrderSet to IndexSet)

- src/lib.rs
We now have indexmap 1.0!
We need to 
1. Document our version requirement (so that others can understand it and use it)
2. Make a sustainable plan for the version requirement in 1.0
I believe we can have a very long lived indexmap 1.x release series if we are careful keepers of the crate. We do then, however, have to deal with a changing Rust landscape, and whatever it will bring. I think it's best to be up front about this: I don't think we want or can stick to a Rust 1.18 minimum requirement forever. I don't either think that we should rush to new versions (I already think the Rust 1.18 requirement is a bit high for the present time, but that can be fixed backwards compatibly..)
> Document minimum rust version and versioning policy

- src/map.rs
- src/set.rs
This method provides functionality to both insert an item and get its index at the same time.
`IndexMap` already provides such functionality with the `Entry` API.
> Add IndexSet::insert_full

- src/map.rs
First of all, thanks a lot for you lovely crate!
I'm using it for some of my pet-projects, and recently I found an [`and_modify`](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.and_modify) method missing in the map's entry API.
My personal use-case is as following: I use a structure like `HashMap<_, NonEmptySet<_>>`, and I need to insert something into that `NonEmptySet`. Since I can't use the `or_insert_with` method (I can't create an empty `NonEmptySet` :) ), I have to first match whether an `Entry` is vacant and manually create a `NonEmptySet` with my element or insert the element into an already existing set if the entry is occupied.
With `and_modify` I can skip the matching part and write something like that:
```rust
mymap
.entry(key) …
```
> Add `and_modify` method to `map::Entry`

- .travis.yml
In `lazy_static 1.1`, they now require Rust 1.21.  We only use it for
benchmarks anyway, but all dev-dependencies still have to be built for
testing.
> Downgrade lazy_static for Rust 1.18 CI

- Cargo.toml
- README.rst
- src/map.rs
- src/set.rs
Resolves two cases from #19. I add only trivial implementations -- for example, for `Drain` implementing of `Debug` not trivial, so I do not add it
> Implementation of Clone, Debug and documentation for structures

- .travis.yml
- Cargo.toml
- README.rst
- src/lib.rs
- tests/quick.rs
Also update the travis script and the README to indicate that MSRV is
1.18 for builds, and 1.30 for development builds.
Fixes #96.
> Update development dependencies

- .travis.yml
- Cargo.toml
- src/lib.rs
- src/map.rs
- src/rayon/map.rs
- src/rayon/mod.rs
- src/rayon/set.rs
- src/set.rs
- `IntoParallelIterator` by value, ref, and ref mut
- Implements both `ParallelIterator` and `IndexedParallelIterator`
- `FromParallelIterator`
- `ParallelExtend` by value and ref copy
> Implement Rayon traits (optional)

- benches/bench.rs
- src/map.rs
- src/set.rs
- tests/equivalent_trait.rs
- tests/quick.rs
This aims to make the performance tradeoffs explicit when removing items.
- New `shift_remove` and `shift_take` perform O(n) removal, like `Vec::remove`
- The existing `swap_*` methods already perform like `Vec::swap_remove`
- Ambiguous `remove` and `take` methods, which currently swap, are deprecated in favor of explicit `shift`/`swap` methods.
Fixes #90.
> Expand removal options

- src/macros.rs
- tests/macros_full_path.rs
This was just fixed in maplit, so copying the same fix to here.
The attribute option fixes the self-referential usage of the macro in
itself, and fixes the macros so they can be used with their full path
(like indexmap::indexmap!(), see tests).
This is backwards compatible, see
https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#local-helper-macros
for more information.
> Fix self-referential usage in indexmap/indexset macros

- src/map.rs
- src/set.rs
Note, these methods are never scheduled to be removed. The warning was
intended to guide the user towards being more explicit about which
removal type they wanted (`swap_remove` or `shift_remove`).
However, seeing how indexmap can be used as a drop in solution for
HashMap, I again am dubious that these warnings should be there.
Documentation for the methods has been improved.
> Remove deprecation warnings on the removal methods again

- .travis.yml
- Cargo.toml
- build.rs
- src/lib.rs
- src/macros.rs
- src/map.rs
- src/set.rs
- test-nostd/Cargo.toml
- test-nostd/src/lib.rs
Recast version of #95 by @leo60228
1. Continue supporting current Rust versions in the default configuration
2. On targets where std is missing, compile as no_std using the feature detection leo added in autocfg (Requires Rust 1.36)
3. There's no feature flag for this, because it's not needed (negative feature flags being awkward), and because it could be considered to be a breaking change
4. Constructor `new` etc is not available without std — one has to use the others like `with_hasher` or `default`. The `indexmap!` macros depend on these as well, and require std too.
This approach, in particular (3) is novel, and thus it is out for wider requests for comments.
A no-std indexmap has been requested by petgraph.
Fixes #94 
Closes #95 
Closes #92
> Support building without libstd

- src/map.rs
- src/set.rs
I wanted a way to access the index but the only way to do that is  by getting the entry and then the index from that which is mutable (and causes issues) or from `get_full` which returns more than what I needed so I added `entry_index`
> Adds entry_index to map.rs

- src/map.rs
- src/set.rs
- tests/quick.rs
Closes #127.
Here's my work so far, just basing it off of what's done in `sort_by()`. Happy to include the more efficient re-indexing as you suggested, @cuviper! Just need to learn how.
> Adding `reverse()` to `IndexMap` & `IndexSet`

- .travis.yml
- Cargo.toml
- test-nostd/Cargo.toml
- test-serde/Cargo.toml
- test-serde/src/lib.rs
We don't actually need any std/alloc features of `serde`, but our
dev-dependency on `serde_test` was indirectly turning on its default
features. However, if we isolate that testing to a separate crate in the
workspace, Cargo will compute the enabled features separately. Now we
can actually enable the `serde-1` feature in `test-nostd` too!
Closes #109.
> Build serde without default features

- src/map.rs
This will close #108 
This doesn't so much improve the entry code rather than abstract away `entry` and `insert` into a `ProbeAction`. This forces monomorphization to give us the insert fast path that doesn't require the additional indirection that entry does.
It also implements `insert_full` on that fast path (`insert` is now just a call to `insert_full`), so that should be much faster as well, since it was formerly implemented in terms of `entry`.
Benchmarks
```
name                                   control ns/iter  variable ns/iter  diff ns/iter  diff %  speedup 
insert_orderedmap_100_000              2,688,143        2,616,739              -71,404  -2.66%   x 1.03 
insert_orderedmap_10_000               275,198          272,283                 -2,915  -1.06%   x 1.01 …
```
> Unify the entry and insert code

- benches/bench.rs
- benches/faststring.rs
I was seeing a lot of variance in benchmark results, and I noticed that
we were using `SmallRng::from_entropy()`. Now we use a fixed seed value,
so we test the same input data every time.
> Use a consistently seeded Rng for benchmark stability

- src/map.rs
- src/set.rs
- `pub fn get_key_value<Q: ?Sized>(&self, key: &Q) -> Option<(&K, &V)>`
- Stabilized in Rust 1.40.
- This is a middle-ground between `get` and our own `get_full` that
includes the index. It's easy enough to add for compatibility.
- `pub fn remove_entry<Q: ?Sized>(&mut self, key: &Q) -> Option<(K, V)>`
- Stabilized in Rust 1.27.
- For `IndexMap`, this also adds `swap_`/`shift_remove_entry` choices.
- These are also a middle-ground between (`swap_`/`shift_`)`remove` and
our own `swap`/`shift_remove_full` that include the index. We don't
have a plain `remove_full` though.
> Add more methods matching the standard HashMap

- .travis.yml
- Cargo.toml
- README.rst
- src/lib.rs
- src/map.rs
- src/map/core.rs
- src/map/core/raw.rs
- src/map_core.rs
- src/set.rs
- src/util.rs
This switches `IndexMapCore` from its bespoke hash table to `hashbrown::raw::RawTable<usize>`, storing just the index into our ordered `entries: Vec<Bucket<K, V>>`. We lose the badge of having no `unsafe` code, but the overall implementation is much simpler, relying on the battle-hardened `hashbrown` for the tricky parts. I have also confirmed that the testsuite passes under `cargo miri`.
I'll post the benchmark comparison in a followup comment, but broadly speaking it appears faster for insertion and lookup, and slower for removal. I think that's a reasonable trade-off for this crate.
As a bonus, I also implemented a proper `reserve` and added `shrink_to_fit`, since they are now pretty straightforward.
cc @Amanieu -- thanks for `hashbrown` and for exposing `RawTable` to make this …
> Switch to hashbrown's RawTable internally

- src/map.rs
- src/rayon/map.rs
- src/rayon/set.rs
- src/set.rs
This is keeping up with rust-lang/rust#58370 (Rust 1.34) and rust-lang/rust#67642 (Rust 1.43). We already had some of the same methods free of bounds, but we can also match the rest. There's no change to any of the actual implementations, so this is only a difference in the API commitment.
> Relax some bounds to match std

- README.rst
The changes from #131 are now reflected in the Background section of the README.
> Update the README for the hashbrown-based implementation

- src/rayon/map.rs
This was missed in #141, where all the other iterators dropped `S: BuildHasher`.
> Relax IntoParallelIterator for &'a mut IndexMap

- src/map.rs
- src/map/core.rs
- src/map/core/raw.rs
- src/set.rs
- src/util.rs
- tests/quick.rs
Rather than just `RangeFull`, this lets us accept any `Range*` type or
even arbitrary `Bound` pairs, matching the signature of `Vec::drain`.
> Expand drain to accept any RangeBounds<usize>

- src/map.rs
- src/set.rs
- tests/quick.rs
```rust
where
IndexMap<K, V, S>: IndexMut<usize, Output = V>,
IndexSet<T, S>: Index<usize, Output = T>,
```
This allows `map[i]` and `set[i]` indexing to access values directly,
panicking if the index is out of bounds, similar to slices.
On maps, this somewhat overlaps with `Index<&Q> + IndexMut<&Q>` where
`Q: Equivalent<K>`. The reference makes this indexing unambiguous, but
it could be confusing to users if the key type is also an integer.
> Implement direct usize indexing

- .travis.yml
The new test command added in e0c627b1bea0f directly followed the prior
command, without `&&`-chaining the result. So if the tests before it
_failed_, we wouldn't notice...
> ci: make sure test commands are `&&`-chained

- .travis.yml
- Cargo.toml
- README.rst
- build.rs
If you know you need "std", e.g. relying on default `S = RandomState`,
then you can enable this feature to force it on, bypassing target
detection. This may help scenarios where `autocfg` fails detection, like
issue #144, but at the very least it will speed up the build script by
avoiding extra `rustc` invocations.
> Add a feature to explicitly enable "std"

- .travis.yml
- Cargo.toml
- README.rst
Note: This increases the MSRV to Rust 1.36.
> Update to hashbrown 0.9

- src/lib.rs
- src/serde.rs
The optional dependency on `serde` creates an implicit feature, but
we've only been enabling that implementation with `"serde-1"`. Now you
can directly enable `"serde"` to get full use, and `"serde-1"` is just
kept for compatibility.
If we ever need a `"serde-2"`, that can depend on package renaming.
Closes #84.
> Let feature "serde" work as well as "serde-1"

- README.rst
- src/lib.rs
[Seems the current MSRV is 1.36](https://github.com/bluss/indexmap/pull/152), but some docs still say it's 1.32.
> Fix outdated docs

- src/map.rs
- src/map/core.rs
- src/map/core/raw.rs
- src/set.rs
```rust
impl<K, V, S> IndexMap<K, V, S> {
pub fn truncate(&mut self, len: usize);
pub fn split_off(&mut self, at: usize) -> Self where S: Clone;
pub fn first(&self) -> Option<(&K, &V)>;
pub fn first_mut(&mut self) -> Option<(&mut K, &mut V)>;
pub fn last(&self) -> Option<(&K, &V)>;
pub fn last_mut(&mut self) -> Option<(&mut K, &mut V)>;
pub fn swap_indices(&mut self, a: usize, b: usize);
}
impl<T, S> IndexSet<T, S> {
pub fn truncate(&mut self, len: usize);
pub fn split_off(&mut self, at: usize) -> Self where S: Clone;
pub fn first(&self) -> Option<&T>;
pub fn last(&self) -> Option<&T>;
pub fn swap_indices(&mut self, a: usize, b: usize);
}
```
I would prefer `&K` instead of `&mut K` in `IndexMap::first_mut` and
`last_mut`, but this is consistent with the existing `get_index_mut`.
> Add more Vec/slice-like methods to maps and sets

- Cargo.toml
- src/lib.rs
- src/serde.rs
- src/serde_seq.rs
- test-serde/Cargo.toml
- test-serde/src/lib.rs
Our default serde implementation treats `IndexMap` as a normal map,
which is often a nice representation in serialization formats, but they
might not preserve the order.
This commit adds a `serde_seq` module with `serialize` and `deserialize`
functions, which makes it suitable for serde's field attributes, like
`#[serde(with = "indexmap::serde_seq")]`. This mode treats `IndexMap` as
a sequence of `(key, value)` pairs, which should always preserve order.
Closes #156.
> Add serde_seq to serialize maps as a sequence 

- src/map.rs
- src/map/core.rs
- src/map/core/raw.rs
The new behavior is consistent with `HashMap` entries in the standard
library, and it has been our intent to match that API when possible.
Fixes #169.
> Change OccupiedEntry::key() to return the existing key in the map

- Cargo.toml
- benches/bench.rs
- src/map.rs
- src/rayon/map.rs
- src/rayon/set.rs
- src/set.rs
- tests/quick.rs
`Copied` is available since Rust 1.36 and Rayon 1.2.
> Prefer copied() iterators instead of cloned()

- src/lib.rs
- src/map.rs
This adds equivalents of the same methods of HashMap and BTreeMap stabilized in Rust 1.54.
- https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.into_keys
- https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.into_values
- https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.into_keys
- https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.into_values
> Add IndexMap::into_{keys,values}

- src/macros.rs
- src/map.rs
- src/rayon/map.rs
- src/set.rs
This is a variety of small improvements for the iterators:
- Use `double_ended_iterator_methods!`
- Specialize `nth_back` just like `nth`
- Add `rfold` for iterators built on `Chain`
- `impl ExactSizeIterator for Drain`
- `impl FusedIterator` for all serial iterators
- `impl Debug for Drain`, `ParIterMut`, and `ParValuesMut`
> Iterator polish

- src/map.rs
- src/set.rs
Most other methods specify how they affect insertion order; this PR adds those notes to `.pop()` as well.
> Clarify docs for `.pop()`

- .github/workflows/ci.yml
- Cargo.toml
- src/lib.rs
- src/macros.rs
- src/rayon/mod.rs
- src/rustc.rs
This adds basic `IntoParallelIterator` support for the `rustc-rayon` fork of `rayon`, as needed by rust-lang/rust#90842 (cc @pierwill). The optional dependency is commented as "internal" for `rustc`'s use alone, and we should feel free to make breaking changes like semver-bumps in coordination with compiler updates.
> Add minimal support for rustc-rayon

- src/map.rs
- src/map/core.rs
- src/set.rs
Closes #202 
If you need `hash_builder` that can be made in the static context, consider [`ahash`](https://docs.rs/ahash/*/ahash/struct.RandomState.html#method.with_seeds).
> Make with_hasher const

- build.rs
- src/map.rs
- src/set.rs
This patch adds `IndexMap::from(array)` and `IndexSet::from(array)` to match the API for `HashMap`, `HashSet`, etc. as of https://github.com/rust-lang/rust/pull/84111.
> Add `IndexMap::from(array)` and `IndexSet::from(array)`

- src/map.rs
- src/rayon/map.rs
- src/rayon/set.rs
- src/set.rs
> feat: add unstable sorting methods

- .github/workflows/ci.yml
- src/map.rs
- src/set.rs
- tests/quick.rs
This adds a builder to run `cargo miri` in order to check for certain classes of undefined behavior.
> Add miri builder

- Cargo.toml
- RELEASES.rst
- src/set.rs
* Add a new `replace_full` method, which behaves like `replace` but also
returns the index of the item.
* Clarify that `replace` and `replace_all` do not modify the replaced
item's insertion order in the documentation.
* Add test coverage for `replace` and `replace_full` by copying the
existing tests for `insert` and `insert_full`.
Closes #221
> Add a `replace_full` method on `IndexSet`

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- RELEASES.md
- src/lib.rs
- src/map.rs
- src/map/slice.rs
- src/rayon/map.rs
- src/rayon/set.rs
- src/serde_seq.rs
- src/set.rs
- src/set/slice.rs
- src/util.rs
Both `map::Slice<K, V>` and `set::Slice<T>` are true DSTs, simply wrapping `[Bucket]`, created by reference either indexing with ranges or calling `as_slice()` or `as_mut_slice()`. They support many of the normal indexing methods of slices, like splitting, but nothing that would change the order or require hashing. They also reuse the iterator types from map and set. `Slice` equality _does_ consider the order of the elements, and this is followed by `PartialOrd`, `Ord`, and `Hash` as well.
> Add dynamically-sized slices of maps and sets

- src/map/core.rs
- src/map/slice.rs
- src/serde_seq.rs
- src/set/slice.rs
Just a small improvement for fun, plus a few other small fixes.
> Use first-class patterns for split_first/last

- RELEASES.md
- src/map.rs
- src/map/core.rs
- src/set.rs
- tests/quick.rs
This moves the position of a key-value pair from one index to another by
shifting all other pairs in-between, making this an O(n) operation.
This could be used as a building-block for other operations, like #173
which wants to insert at a particular index. You can `insert_full` to
insert it _somewhere_, then choose whether to `move_index` depending on
whether you want to also change pre-existing entries.
> Add move_index to change the position of an entry

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- src/lib.rs
This reverts commit 8a571c6d68cb38c283d563ff6972613e0eea4111.
See https://github.com/rust-lang/hashbrown/pull/343.
> Allow compiling on 1.56.0

- .github/workflows/ci.yml
- Cargo.toml
- RELEASES.md
- src/arbitrary.rs
- src/lib.rs
This implements both `arbitrary::Arbitrary` and `quickcheck::Arbitrary`
behind optional dependencies on their respective crates.
> impl Arbitrary for IndexMap and IndexSet

- .github/workflows/ci.yml
- Cargo.toml
- RELEASES.md
- src/arbitrary.rs
- src/lib.rs
- impl Arbitrary for IndexMap and IndexSet
- Add an Arbitrary release note
- Release 1.9.2
> Backport Arbitrary (#246) and release 1.9.2

- src/map/iter.rs
- src/set/iter.rs
In fact, these are directly relying on the same methods from `std`
iterators, since we build our iterators as simple wrappers on those.
> Add more slicing methods to iterators, like std

- Cargo.toml
- RELEASES.md
- src/arbitrary.rs
- src/lib.rs
- src/macros.rs
- src/map.rs
- src/map/serde_seq.rs
- src/rayon/map.rs
- src/rayon/set.rs
- src/serde.rs
- src/serde_seq.rs
- src/set.rs
- test-serde/src/lib.rs
In this PR I've added a couple of commits to:
1. Use the [`doc_cfg`](https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html) feature to improve readability of certain items in the crate which are locked behind feature flags.
2. Update the crate-level documentation for what the feature flags actually do.
I'm hoping this will improve clarity on the `serde` feature; it wasn't immediately clear to me that the `serde` feature enabled `Serialize` and `Deserialize` implementations, and that the functions in `serde_seq` were actually an alternative implementation for `IndexMap` specifically.
I also think that we should consider moving the `serde_seq` module from the crate root into the `map` module (similar to how the `rayon` module is organised under the `map` and `set` …
> Improve feature flag documentation

- src/map/iter.rs
- src/map/tests.rs
- src/set/iter.rs
- src/set/tests.rs
This matches `Default` implementations for HashMap and HashSet introduced in Rust 1.70 (https://github.com/rust-lang/rust/pull/99929/).
> Implement Default for iterators

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- RELEASES.md
- src/lib.rs
- src/map/core/raw.rs
See https://github.com/rust-lang/hashbrown/blob/v0.14.0/CHANGELOG.md.
Bumps the MSRV to 1.64.
Related #243.
> Upgrade to hashbrown 0.14 (MSRV 1.64)

- src/map/core.rs
- src/map/core/raw.rs
- src/set.rs
With `find_or_find_insert_slot` and `insert_in_slot`, we can avoid an
extra insertion lookup after checking for existence. However, that also
reserves space for a new entry *before* checking existence, so it's a
little biased towards new items. For that reason, we're not using this
for map `entry` or set `replace`, as both imply a little more weight on
the expectation that it may already exist.
> Use hashbrown's new single-lookup insertion

- Cargo.toml
- RELEASES.md
- **MSRV**: Rust 1.64.0 or later is now required.
- The `"std"` feature is no longer auto-detected. It is included in the
default feature set, or else can be enabled like any other Cargo feature.
- The `"serde-1"` feature has been removed, leaving just the optional
`"serde"` dependency to be enabled like a feature itself.
- `IndexMap::get_index_mut` now returns `Option<(&K, &mut V)>`, changing
the key part from `&mut K` to `&K`. There is also a new alternative
`MutableKeys::get_index_mut2` to access the former behavior.
- The new `map::Slice<K, V>` and `set::Slice<T>` offer a linear view of maps
and sets, behaving a lot like normal `[(K, V)]` and `[T]` slices. Notably,
comparison traits like `Eq` only consider items in order, rather than hash
lookups, and slices even implement `Hash`.
- …
> Release 2.0.0

- .github/workflows/ci.yml
This builds the crate with [`direct-minimal-versions`](https://doc.rust-lang.org/cargo/reference/unstable.html#direct-minimal-versions) checking if the crate actually builds with the minimal dependency versions specified.
Using [`taiki-e/install-action`](https://github.com/marketplace/actions/install-development-tools) to install [`cargo-hack`](https://crates.io/crates/cargo-hack) specifically to use `--remove-dev-deps` to get the actual minimal versions users can use. If these CI dependencies are undesirable, I can make an out-of-workspace sub-crate that can have it's own lockfile without any dev-dependencies.
Cc #271.
> Test `direct-minimal-versions`

- src/set.rs
This PR fixes [this comment in #187](https://github.com/bluss/indexmap/pull/187#issuecomment-1678785827).
In addition to just adding an explanation only about `get_index_of()` method, I added `Complexity` section to explain `IndexSet<T, S>` is internally just an `IndexMap<T, (), S>`.
> Improve explanation about `IndexSet`'s complexity.

- src/map/slice.rs
- src/set/slice.rs
* `pub const fn map::Slice::new<'a>() -> &'a Self`
* `pub fn map::Slice::new_mut<'a>() -> &'a mut Self`
* `pub const fn set::Slice::new<'a>() -> &'a Self`
In addition, the existing `len` and `is_empty` are now `const fn`.
> Add `Slice::new` and `new_mut` for empty slices

- src/map.rs
- src/map/slice.rs
- src/map/tests.rs
- src/set.rs
- src/set/slice.rs
- src/set/tests.rs
This is a start on fixing #281.
I copied the implementation of these methods from std, except for `binary_search_by` where I used std directly. Alternatively we could have all implementations directly forward to `.as_slice().foobar` or `.entries.foobar`,  if you would prefer that.
I left off the plane `binary_search{_keys}` on set and map, because they already provide a `O(1)` way to look up the index for a key. I left them in on `Slice` because they do not.
For documentation I adapted the first sentence of std, and provided a link to std.
how would you like to see these tested?
> add binary_search and friends

- src/lib.rs
The `html_root_url` currently links to an old version of the docs, so if you run `cargo doc --no-deps` on a downstream package that depends on `indexmap@2.1.0`, intra-doc links to `indexmap` types will resolve to `indexmap@1.9.3` on docs.rs.
> Remove doc `html_root_url`

- src/map.rs
- src/map/core.rs
- src/map/tests.rs
This change adds a method `get_index_entry` to `IndexMap`, which is the by-index counterpart to `entry`. The returned struct `IndexedEntry` provides the same methods as `OccupiedEntry`, except `replace_key`.
A concrete use case where I found this useful is having a `map: IndexMap<_, Vec<_>>` with the invariant that each `Vec` is non-empty. Imagine we want to pick an entry at a random index and pop a value from the `Vec`. Without this change we'd have to use `get_mut_index` and `swap_remove_index`, and ensure that we use the same index. With `get_index_entry` we can write:
```rust
let mut e = map.get_index_entry(index).unwrap();
let v = e.get_mut();
let x = v.pop().unwrap();
if v.is_empty() {
e.swap_remove();
}
```
> Add method to get a map entry by index

- src/map.rs
- src/map/iter.rs
While `Index<usize> for IndexMap` accesses a map's values, indexing through `IndexMap::keys` offers an alternative to access a map's keys instead.
Resolves #284.
> `impl Index<usize> for Keys`

- README.md
- src/map.rs
- src/map/core.rs
- src/map/core/raw.rs
- src/set.rs
It's a frequent point of confusion that these methods disrupt the order
(by swapping the last item), but that choice was made for performance.
The alternative `shift_*` removals are also disruptive to indices, and
require O(n) updates instead of O(1).
The deprecation notes recommend instead choosing a swap/shift method
explicitly. This doesn't mean that we'll ever actually _remove_ these
deprecated methods, since they are still nice to have when acting as a
drop-in `HashMap` replacement, but the warning will hopefully help avoid
surprises.
Resolves #241.
Resolves #220.
> Re-deprecate `remove`, `remove_entry`, and `take`

- src/map.rs
- src/map/core.rs
- src/map/iter.rs
- src/set.rs
- src/set/iter.rs
`IndexMap::splice` and `IndexSet::splice` will drain the specified
range, and then insert items from an iterator to replace that range.
This is like `Vec::splice`, except if any new keys match the retained
entries outside the range, then those keep their relative position.
Resolves #274.
> Add splicing iterators

- src/map.rs
- src/map/core.rs
- src/map/core/raw_entry_v1.rs
We usually wait for the standard library to stabilize APIs so we can match them as much as possible, but the future of raw entries in rust-lang/rust#56167 is uncertain. For folks who really want it now, this PR offers an opt-in trait `RawEntryApiV1` without polluting our *inherent* method namespace.
The V1 suffix is basically representing a snapshot of what `std` currently has, as of Rust 1.75. If they later change in compatible ways, we can extend ours to keep up, or else we can consider a V2. If `std` finally stabilizes a raw entry API, we will match that in our inherent methods, without an intermediate trait. We won't be able to remove the old traits without a semver breaking change, but they can at least be `#[deprecated]`.
Resolves #166.
> Add an opt-in trait for "unstable" raw entries

- Cargo.toml
- RELEASES.md
- src/map/core/raw_entry_v1.rs
This was a bad copy-paste error from `key_mut`. While this is a breaking change, it has been short enough time that I'm going to treat this as a bug fix. I already yanked 2.2.0 as well.
> Fix `RawOccupiedEntryMut::into_key`, release 2.2.1

- Cargo.toml
- RELEASES.md
- src/map/core/raw_entry_v1.rs
The `std`-matching methods of `RawEntryBuilder` only return `(&K, &V)`,
but the index is also useful when working with `IndexMap`.
```rust
impl<'a, K, V, S> RawEntryBuilder<'a, K, V, S> {
/// Access an entry by hash, including its index.
pub fn from_hash_full<F>(self, hash: u64, is_match: F) -> Option<(usize, &'a K, &'a V)>
where
F: FnMut(&K) -> bool,
/// Access the index of an entry by hash.
pub fn index_from_hash<F>(self, hash: u64, is_match: F) -> Option<usize>
where
F: FnMut(&K) -> bool,
}
```
In addition, the `RawEntryMut` enum can report its index by forwarding
to the existing methods on its variants.
```rust
impl<'a, K, V, S> RawEntryMut<'a, K, V, S> {
/// Return the index where the key-value pair exists or may be inserted.
pub fn index(&self) -> usize
}
```
> Add indexing methods to raw entry

- RELEASES.md
When services like https://github.com/renovatebot/renovate open [dependency update pull requests](https://github.com/rust-lang/crates.io/pull/8043) they try to find a corresponding changelog entry to let the developers know what changes this dependency update includes.
The current format of the `RELEASES.md` file with its nested lists appears to be uncommon enough to not get recognized by at least renovatebot.
This changes the format to use `h2` elements for the versions, which should allow renovatebot to pick up the contents and generally renders in a slightly nicer way :D
Best reviewed in "ignore whitespace" mode: https://github.com/indexmap-rs/indexmap/pull/306/files?w=1 😉 
/cc @cuviper
> Releases: Adjust markdown format

- src/map.rs
- src/map/core.rs
- src/map/core/entry.rs
- src/map/core/raw.rs
- src/map/core/raw_entry_v1.rs
- src/map/tests.rs
- src/set.rs
- src/set/tests.rs
- tests/quick.rs
For `IndexedEntry`, `OccupiedEntry`, and `RawOccupiedEntryMut`, this
adds `move_index` and `swap_indices` methods that work like the
top-level `IndexMap` methods using the current index of the entry.
For `VacantEntry` this adds `shift_insert`, while `RawVacantEntryMut`
adds `shift_insert` and `shift_insert_hashed_nocheck`, offering a way to
insert at a particular index while shifting other entries as needed.
Finally, for `IndexMap` and `IndexSet` this adds `shift_insert` using
`OccupiedEntry::move_index` or `VacantEntry::shift_insert`.
> Add more indexed methods to entries

- src/map.rs
We already avoid hashing for get/remove on empty maps, but we can also
do this for single-entry maps. Even with a cheap hash function, a single
equality check ought to be faster than any hash table lookup.
> Avoid hashing for single-entry maps

- src/map.rs
- src/map/core/entry.rs
- src/set.rs
- tests/quick.rs
```rust
impl<K: Hash + Ord, V, S: BuildHasher> IndexMap<K, V, S> {
pub fn insert_sorted(&mut self, key: K, value: V) -> (usize, Option<V>);
}
impl<'a, K: Ord, V> VacantEntry<'a, K, V> {
pub fn insert_sorted(self, value: V) -> (usize, &'a mut V);
}
impl<T: Hash + Ord, S: BuildHasher> IndexSet<T, S> {
pub fn insert_sorted(&mut self, value: T) -> (usize, bool);
}
```
These use a `binary_search` to find the sorted index, then `shift_insert`, so they are O(n) overall. The insertion index is unspecified if the existing entries are not already sorted, but it will still act like a consistent `shift_insert` at that point.
Closes #89.
> Add `insert_sorted`

- src/map/serde_seq.rs
- src/serde.rs
This is the same limit that serde itself has used since serde-rs/serde#2495.
> Limit preallocation in deserializers

- .github/workflows/ci.yml
- Cargo.toml
- src/borsh.rs
- src/lib.rs
Add support to serialize maps and sets with [`borsh`](https://lib.rs/crates/borsh).
> Add `borsh` serialization support

- Cargo.toml
- RELEASES.md
- src/borsh.rs
- src/lib.rs
- src/map.rs
- src/map/core/raw_entry_v1.rs
- src/map/mutable.rs
- src/map/slice.rs
- src/set.rs
- src/set/mutable.rs
- src/set/slice.rs
This adds `set::MutableValues` as an opt-in trait for accessing `IndexSet` values by mutable reference, akin to `map::MutableKeys`. The implementation simply forwards to the map implementation while discarding the `()` inner "value".
Unlike `IndexMap`, `IndexSet` doesn't have regular `get_full_mut` or `get_index_mut` methods, so the "2" suffix here isn't really necessary, but I thought it might be better to stay consistent with `MutableKeys` on that.
Closes #322
> Opt-in mutable access on IndexSet, release 2.2.6

- Cargo.toml
- RELEASES.md
- src/map.rs
- src/map/core/entry.rs
- src/map/iter.rs
- src/map/mutable.rs
- src/map/tests.rs
See toml-rs/toml#765 for an example use case
Fixes #334
> Alow Mutating Entry keys and iterator keys

- Cargo.toml
- README.md
- RELEASES.md
- src/map.rs
- src/set.rs
These are like a mix of `BTreeMap::append` / `BTreeSet::append` and `Vec::append`, updating existing entries or else appending new entries, while keeping the original order.
```rust
pub fn IndexMap<K, V, S>::append<S2>(&mut self, other: &mut IndexMap<K, V, S2>)
pub fn IndexSet<T, S>::append<S2>(&mut self, other: &mut IndexSet<T, S2>)
```
Closes #336.
> Add `append` methods

- src/map/core/entry.rs
- src/map/core/raw.rs
- src/map/tests.rs
* `From<OccupiedEntry> for IndexedEntry` is trivially O(1).
* `From<IndexedEntry> for OccupiedEntry` is O(1) *average*, requiring a `RawTable` search for the bucket.
Either way, there's not much reason to convert unless you're normalizing different lookup results somewhere, but it's easy enough to support this that we might as well.
> Implement `From` between `IndexedEntry` and `OccupiedEntry`

- src/map.rs
- src/map/tests.rs
- src/set.rs
- Add `first_entry` and `last_entry` similar to `BTreeMap`'s, except ours returns `IndexedEntry` instead of `OccupiedEntry`, avoiding the `RawTable` search.
- Add doc aliases for `BTreeMap`/`BTreeSet`-like methods:
- `first_key_value` is `first`, and `last_key_value` is `last`
- `pop_last` is just `pop` (and we don't have `pop_first`)
> Add a few nods to `BTreeMap`/`Set`

- src/map.rs
- src/map/tests.rs
- src/set.rs
The way `shift_insert` works is a little weird around *existing* entries, because it's not possible to move them to `index == len()` -- that only works when inserting new entries. This caveat is now documented and directly asserted, so the panic will be clearer than the deeper bounds-check panic we were throwing before.
As an alternative, I've also added `insert_before` which is looser about the exact index when moving entries. There's no difference for new entries, but existing entries might move to `index - 1` if that keeps them right before the entry at the given index, or the end point. In this case, all indices in `0..=len()` are always valid choices.
That new semantic is also a little better for the implementation of `insert_sorted`, although that only matters in the case where …
> Assert bounds in `shift_insert` and add `insert_before`

- src/map/tests.rs
This is a targeted test to make sure we cover all the heuristic edge
cases in `erase_indices`, used by `drain` and other methods.
I found a failure from `cargo mutants` where we still passed tests after
`erase_indices_sweep` was replaced with an empty body. I was concerned
because that function contains `unsafe` code, so we *really* need it
tested. It turns out that we do *sometimes* hit that in `quickcheck`
tests, but might miss that if we're randomly unlucky, so this PR adds a
new test that will hit all the edge cases every time.
> Test the various heuristics of `erase_indices`

- src/map/core.rs
- src/map/tests.rs
It did already panic as expected, but with a confusing message if the `to` index was out of bounds. Now we have a direct bounds check for that at the start, just as there already was for the `from` index.
> Add an explicit bounds check in `move_index`

- Cargo.toml
- RELEASES.md
- src/map/core.rs
- src/map/core/entry.rs
- src/map/core/raw_entry_v1.rs
This matches the `HashMap` side of rust-lang/rust#65225, which is stabilizing in Rust 1.83.
> Add `{Entry,VacantEntry}::insert_entry`

- src/lib.rs
If a project has the following in its manifest:
```
[dependencies]
borsh = { version = "1.5.3", features = ["derive"] }
indexmap = { version = "2.7.0", features = ["borsh"] }
```
then the following error is returned by `cargo`:
```
error: cyclic package dependency: package `borsh v1.5.3` depends on itself. Cycle:
package `borsh v1.5.3`
... which satisfies dependency `borsh = "^1.2"` (locked to 1.5.3) of package `indexmap v2.7.0`
... which satisfies dependency `indexmap = "^2.3.0"` (locked to 2.7.0) of package `toml_edit v0.22.22`
... which satisfies dependency `toml_edit = "^0.22.20"` (locked to 0.22.22) of package `proc-macro-crate v3.2.0`
... which satisfies dependency `proc-macro-crate = "^3"` (locked to 3.2.0) of package `borsh-derive v1.5.3`
... which satisfies dependency …
```
> Mention cyclic dependency in main rustdocs

- Cargo.toml
- src/lib.rs
remove fxhash example and dep as [fxhash is unmaintained](https://github.com/rustsec/advisory-db/issues/2185)
> remove fxhash example and dep

- src/map.rs
- src/map/core.rs
- src/map/core/entry.rs
- src/map/iter.rs
- src/set.rs
- src/set/iter.rs
- src/util.rs
Currently, `indexmap` panic messages aren't really helpful, and this PR adds `#[track_caller]` attributes to functions that may panic, for better understanding where to actually look for the panic, and uses the same panic messages that standard collections do with more details.
Seems like `#[track_caller]` is compatible with no_std, and it shouldn't break anything.
> Improve panic messages and add `#[track_caller]` attribute to functions that may panic

- src/map/core.rs
In `core::RefMut::insert_unique`, used by `insert_entry` and others, we
were calling `reserve_entries` *before* the table insert, which defeats
the goal of matching capacities. We can't directly call that after table
insert though, because we'll be holding an `OccupiedEntry` that prevents
looking at the table itself. Instead, this code path now uses a more
typical doubling growth on the entries `Vec` itself, but still enhanced
by considering `MAX_ENTRIES_CAPACITY` as well.
> Improve memory reservation for `insert_entry`

- src/map/iter.rs
Both are valid English, but we use "indices" consistently everywhere else, and that's generally more common in technical contexts.
> Correct "indexes" to "indices" in `Keys` doc

- src/map/slice.rs
- src/set/slice.rs
- src/util.rs
Added comparisons between `Slice` and bare slices and arrays:
```rust
impl<K, V, K2, V2> PartialEq<[(K2, V2)]> for map::Slice<K, V>
where
K: PartialEq<K2>,
V: PartialEq<V2>,
impl<K, V, K2, V2> PartialEq<map::Slice<K2, V2>> for [(K, V)]
where
K: PartialEq<K2>,
V: PartialEq<V2>,
impl<K, V, K2, V2, const N: usize> PartialEq<[(K2, V2); N]> for map::Slice<K, V>
where
K: PartialEq<K2>,
V: PartialEq<V2>,
impl<K, V, const N: usize, K2, V2> PartialEq<map::Slice<K2, V2>> for [(K, V); N]
where
K: PartialEq<K2>,
V: PartialEq<V2>,
impl<T, U> PartialEq<[U]> for set::Slice<T>
where
T: PartialEq<U>,
impl<T, U> PartialEq<set::Slice<U>> for [T]
where
T: PartialEq<U>,
impl<T, U, const N: usize> PartialEq<[U; N]> for set::Slice<T>
where
T: PartialEq<U>,
impl<T, const N: usize, U> PartialEq<set::Slice<U>> for …
```
> `impl PartialEq` between `Slice` and `[]`/arrays

- src/lib.rs
- src/macros.rs
Closes #379.
I'm adding `indexmap_with_default` and `indexset_with_default` which should be no-std.
Thanks @JayWhite2357 for providing a solution in [Proof of SQL](https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/crates/proof-of-sql/src/base/map.rs) which we are upstreaming!
> feat: add no_std macros `indexmap_with_default` and `indexset_with_default`

- Cargo.toml
- RELEASES.md
- Added `indexmap_with_default!` and `indexset_with_default!` to be used with
alternative hashers, especially when using the crate without `std`.
- Implemented `PartialEq` between each `Slice` and `[]`/arrays.
- Removed the internal `rustc-rayon` feature and dependency.
> Release 2.8.0

- src/macros.rs
Currently the doc for `indexmap_with_default` and `indexset_with_default` mention `core::hash::BuildHasherDefault` but don't provide any hyperlink to [its page](https://doc.rust-lang.org/beta/core/hash/struct.BuildHasherDefault.html). We can easily fix this so that it is easier for people to use the two macros.
> docs: provide link to `core::hash::BuildHasherDefault` in `macros.rs` docs

- src/lib.rs
- src/map.rs
- src/map/slice.rs
- src/map/tests.rs
`std::collections::HashMap` is adding `get_many_mut` in https://github.com/rust-lang/rust/issues/97601 and I'm working on replacing some uses of that hash map with this one where some of the code uses `get_many_mut` (currently only a single location in rustc) so I would appreciate it if `indexmap::IndexMap` could provide the same interface.
This code uses a decent amount of unsafe compared to the rest of the file and I saw the comment in lib.rs on having almost all unsafe code in raw.rs but I couldn't figure out how to move parts of my implementation there as it is mostly dealing with initializing the array. I tried to use `array::map` to avoid all unsafe but couldn't quite get it to work with the lifetimes and the lambda.
If you want this change, I'll also write some docs.
> Implement get_disjoint_mut (previously get_many_mut)

- Cargo.toml
- src/borsh.rs
- src/lib.rs
The real `#[deprecated]` attribute doesn't work for trait implementations,
but we can get close by mimicking the message style for documentation.
Use the "indexmap" feature added in `borsh v1.5.6` instead, solving the circular dependency.
Fixes #383.
> Deprecate the "borsh" feature

- Cargo.toml
- RELEASES.md
- Added a `get_disjoint_mut` method to `IndexMap`, matching Rust 1.86's
`HashMap` method.
- Added a `get_disjoint_indices_mut` method to `IndexMap` and `map::Slice`,
matching Rust 1.86's `get_disjoint_mut` method on slices.
- Deprecated the `borsh` feature in favor of their own `indexmap` feature,
solving a cyclic dependency that occured via `borsh-derive`.
> Release 2.9.0

- RELEASES.md
**Description:**  
This PR corrects a minor typo in the RELEASES.md file, changing "occured" to the correct spelling "occurred" for improved documentation quality.
> Fix typo in changelog: "occured" → "occurred"

- src/map.rs
- src/map/tests.rs
- src/set.rs
> Add `insert_sorted_by{,_key}` methods for map/set

- src/map.rs
- src/map/core/entry.rs
- src/map/tests.rs
- src/set.rs
- tests/quick.rs
* It's generally better for closures to be the last argument, if only for cleaner formatting
* These methods make sense on `VacantEntry` as well, since that already has `insert_sorted`
* `insert_sorted_by` now takes *two* entries for comparison, so you don't have to capture a separate copy of the key/value that you're inserting. This is also consistent with the existing `sort_by` and `sorted_by` methods.
> Tweak and extend `insert sorted by`{,`_key`} methods

- Cargo.toml
- RELEASES.md
- Added a `get_key_value_mut` method to `IndexMap`.
- Removed the unnecessary `Ord` bound on `insert_sorted_by` methods.
> Release 2.11.1

- Cargo.toml
- src/lib.rs
- src/map/serde_seq.rs
- src/serde.rs
This crate does not make use of serde derive macros, thus it can depend on `serde_core` instead of `serde` to speed up users' compile times.
See the documentation of [`serde_core`](https://docs.rs/serde_core) for more details.
> Depend on `serde_core` instead of `serde`

- Cargo.toml
- RELEASES.md
- Make the minimum `serde` version only apply when "serde" is enabled.
> Release 2.11.3
