- src/lib.rs
* match the implementation of the underlying iterators
> Improve implementation of iterators

- src/lib.rs
- tests/quick.rs
> Implement .values() and .values_mut()

- .travis.yml
- src/lib.rs
> Fix 32-bit compile

- src/lib.rs
> Added index() method for OccupiedEntry

- src/serde.rs
- tests/serde.rs
Although serialization was implemented, deserialization wasn't.
I've added a test for fnv hashers to prevent any regressions ;)
> Fix serde deserialization for custom hashers.

- src/set.rs
This commit specifies current re-insertion behavior, which does not
perturb insertion order, making such guarantee explicit in docstrings.
It also introduces a duplicate-insert test to ensure the behavior
won't have regressions.
> set: specify re-insertion behavior

- src/map.rs
P for Parity :) In response to https://github.com/bluss/indexmap/pull/76#issuecomment-410063622
> Add `or_default` method to `map::Entry`

- Cargo.toml
- README.rst
> Release 1.0.2

- README.rst
- src/serde.rs
> Implement IntoDeserializer for IndexMap/IndexSet

- .travis.yml
- benches/bench.rs
- benches/faststring.rs
Also make sure the benches are built by travis (but not run).
And fix one unrelated warning in bench code.
> Fix compliation of benches with rand 0.6

- Cargo.toml
- README.rst
> Release 1.3.2

- .travis.yml
- Cargo.toml
- benches/bench.rs
- src/lib.rs
> Test from Rust 1.32 and update rand & quickcheck

- src/map.rs
- src/set.rs
This is a suggested fix to #119 
Fixes #119
> Rename entry_index to get_index_of

- .github/workflows/ci.yml
- Update to actions/checkout@v3
- Switch from actions-rs/toolchain to dtolnay/rust-toolchain
> Update and simplify the CI workflow

- RELEASES.md
- src/lib.rs
- src/map.rs
- src/map/core.rs
- src/map/tests.rs
- src/set.rs
- src/set/tests.rs
- Add `reserve_exact`, `try_reserve`, `try_reserve_exact`
- Be more careful about reserving entries capacity
> Add more reservation abilities

- src/map/core.rs
- src/set.rs
This pull request fixes some typos.
> Fix some typos

- src/map.rs
- src/set.rs
> Document the lower-bound semantics of capacity

- .github/workflows/ci.yml
- Cargo.toml
- ci: upgrade to actions/checkout@v4
- Upgrade dev-dep itertools to 0.12
- Allow `clippy::style`
> Misc test updates

- .github/workflows/ci.yml
- ci: Use a single action to collect final status
- ci: Simplify toolchain in minimal-versions
- ci: Add a registry cache for git protocol
> More CI updates

- .github/workflows/ci.yml
- src/map.rs
- src/map/core.rs
- src/map/core/raw.rs
- src/set.rs
... but also add `--all-features` to CI so we're sure it builds.
> Fully mask the `"test_debug"` code from normal builds

- Cargo.toml
- benches/bench.rs
- benches/faststring.rs
- **Switch to fastrand for bench shuffling**
- **Drop lazy_static for LazyLock**
> Simplify benchmark dependencies
